# Generated by Django 5.2.17 on 2026-08-19 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL', 'Initial Stock'), ('SALE', 'Store Sale Order'), ('RESTOCK', 'Supplier Restock'), ('ADJUSTMENT', 'Manual Audit Adjustment'), ('SESSION_USAGE', 'Used In Salon Session'), ('RETURN', 'Customer Return')], max_length=25)),
                ('quantity_delta', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Order or Booking reference ID', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
