# Generated by Django 5.2.17 on 2026-08-19 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(db_index=True, max_length=254)),
                ('guest_phone', models.CharField(max_length=30)),
                ('guest_address', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid & Confirmed'), ('CONFIRMED', 'Confirmed'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Original service price snapshot', max_digits=12)),
                ('product_addon_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final payable NGN amount', max_digits=12)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_products', to='bookings.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_usages', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='bookings_bo_booking_b730a0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_email', 'status'], name='bookings_bo_guest_e_2f0e25_idx'),
        ),
    ]
