# Generated by Django 5.2.17 on 2026-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('email_type', models.CharField(choices=[('ACCOUNT_WELCOME', 'Account Welcome'), ('PASSWORD_RESET', 'Password Reset'), ('BOOKING_CONFIRMATION', 'Booking Confirmation & QR Code'), ('REMINDER_24H', '24-Hour Appointment Reminder'), ('BOOKING_CANCELLED', 'Booking Cancellation'), ('ORDER_CONFIRMATION', 'Order Confirmation & Receipt'), ('ORDER_STATUS_UPDATE', 'Order Status Update'), ('NO_SHOW_NOTICE', 'No-Show Policy Notification')], max_length=30)),
                ('booking_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
