# Generated by Django 5.2.17 on 2026-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='The Art of Rejuvenation & Haute Coiffure', max_length=200)),
                ('hero_subheadline', models.TextField(default='Experience bespoke salon treatments, restorative spa rituals, and luxury beauty curated for the discerning individual.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('about_title', models.CharField(default='Bespoke Luxury Crafted For Distinction', max_length=200)),
                ('about_content', models.TextField(default='AGAMOS represents the pinnacle of salon, spa, and beauty experiences. Founded on the principle of timeless elegance, every ritual is executed with precision craftsmanship.')),
                ('contact_email', models.EmailField(default='concierge@agamos.com', max_length=254)),
                ('contact_phone', models.CharField(default='+234 800 000 2426', max_length=30)),
                ('address', models.TextField(default='12A Victoria Island Luxury Boulevard, Lagos, Nigeria')),
                ('delivery_flat_fee', models.DecimalField(decimal_places=2, default=3500.0, help_text='Courier flat delivery fee in NGN', max_digits=10)),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com/agamosluxury')),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com/agamosluxury')),
                ('social_tiktok', models.URLField(blank=True, default='https://tiktok.com/@agamosluxury')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_title', models.CharField(blank=True, help_text='e.g. Fashion Director, Creative Producer', max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
