# Generated by Django 5.2.17 on 2026-08-19 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('verification_hash', models.CharField(blank=True, help_text='HMAC SHA-256 integrity hash', max_length=64)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='booking_qrs/')),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='bookings.booking')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_qrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
