# Generated by Django 5.2.17 on 2026-08-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Mark entire date as closed (holiday, maintenance, private event)')),
                ('custom_open_time', models.TimeField(blank=True, null=True)),
                ('custom_close_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for schedule override (e.g. Public Holiday, VIP Private Session)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField(default='09:00:00')),
                ('close_time', models.TimeField(default='19:00:00')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30, help_text='Grid step in minutes (e.g. 30 mins)')),
                ('max_concurrent_clients', models.PositiveIntegerField(default=2, help_text='Number of clients that can be served simultaneously')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the salon/spa is open on this day of the week')),
            ],
            options={
                'verbose_name_plural': 'Weekly Availabilities',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, help_text='If set, blocks only this specific service; if null, blocks all services', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
